version: "3.8"

services:
  web:
    build:
      context: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    network_mode: "host"  # Usa diretamente a rede do host
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  static_volume:
  media_volume: